build.sbt, project/Dependencies.scala, project/plugins.sbt
- Update Cinnamon to version 2.16.0
- Bunch of other updates
=> Cinnamon 2.16.0 and other updates

project/Dependencies.scala, project/plugins.sbt
Just patch version updates aside from akka-grpc.
We should release 0.2.0 or why not 1.0.0 from this?
=> Update to latest versions

project/Dependencies.scala
=> Update to Akka HTTP 10.2.8

project/Dependencies.scala
References https://github.com/akka/akka-http/issues/4152
=> bump: Akka umbrella projects

LICENSE, build.sbt
https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
=> Change license

LICENSE, README.md, RELEASE.md, build.sbt, project/Dependencies.scala
* Rename to akka-dependencies
* Add r2dbc
* Remove enhancements
=> Update to Akka 22.10 versions

project/Dependencies.scala
References https://github.com/akka/akka-http/issues/4231
=> bump: Akka HTTP 10.5.0

project/Dependencies.scala
References https://github.com/akka/akka-persistence-jdbc/issues/724
=> bump: Akka Persistence JDBC 5.2.1

project/Dependencies.scala
References https://github.com/akka/akka-management/issues/1156
=> bump: AkkaManagement to 1.4.1

project/Dependencies.scala
References https://github.com/akka/akka-http/issues/4326
=> bump: Akka HTTP 10.5.3

docs/src/main/paradox/index.md
Put the build tool tabs in the same order at all places.
=> Consistent order: Maven, sbt, Gradle

project/Dependencies.scala
References https://github.com/akka/akka-grpc/issues/1939
=> bump: Akka gRPC 2.4.2

project/Dependencies.scala
References https://github.com/lightbend/akka-meta/issues/450
Sans Cinnamon, not bumped/released yet.
=> bump: Akka 24.05 releases

project/Dependencies.scala
References https://github.com/akka/akka/issues/32572
References https://github.com/akka/akka-projection/issues/1223
=> bump: Akka 2.9.7, Akka Projections 1.5.8

project/Dependencies.scala
Refs https://github.com/akka/akka-projection/issues/1280
=> bump: akka-projection 1.6.5

project/Dependencies.scala
Refs https://github.com/akka/akka-persistence-dynamodb/issues/133
=> bump: akka-persistence-dynamodb 2.0.5

project/Dependencies.scala
Refs https://github.com/akka/akka-projection/issues/1301
=> bump: akka-projection 1.6.7

project/Dependencies.scala
References
- https://github.com/akka/akka-grpc/issues/2024
- https://github.com/akka/akka-grpc/releases/tag/v2.5.3
=> bump: Akka gRPC 2.5.3

project/Dependencies.scala
- https://github.com/akka/alpakka/issues/3324
- https://doc.akka.io/libraries/alpakka/current/
- https://github.com/akka/alpakka-kafka/issues/1807
- https://doc.akka.io/libraries/alpakka-kafka/current/
=> Alpakka 9.0.1, Alpakka Kafka 7.0.1

project/Dependencies.scala
References https://github.com/akka/akka-persistence-jdbc/issues/897
=> bump: AP-JDBC 5.5.1

project/Dependencies.scala
References https://github.com/akka/akka-grpc/issues/2055
=> bump: Akka gRPC 2.5.4

project/Dependencies.scala
References
- https://github.com/akka/akka-persistence-r2dbc/releases/tag/v1.3.5
=> bump: Akka Persistence R2DBC 1.3.5

project/Dependencies.scala
- https://github.com/akka/akka-persistence-r2dbc/issues/676
- https://github.com/akka/akka-persistence-r2dbc/releases/tag/v1.3.6
=> bump: akka persistence r2dbc 1.3.6

project/plugins.sbt
- https://github.com/lightbend/akka-paradox-theme/releases/tag/v25.05.1
=> Paradox theme 25.05.1

project/Dependencies.scala
- https://github.com/akka/akka-projection/issues/1347
- https://github.com/akka/akka-projection/releases/tag/v1.6.14
=> bump: akka projection 1.6.14

project/Dependencies.scala
=> bump: Akka 2.9.8 for 24.05

project/Dependencies.scala
- https://github.com/akka/akka-persistence-dynamodb/issues/162
- https://github.com/akka/akka-persistence-dynamodb/releases/tag/v2.0.7
=> bump: akka-persistence-dynamodb 2.0.7

project/Dependencies.scala
- https://github.com/akka/akka-persistence-dynamodb/issues/162
- https://github.com/akka/akka-persistence-dynamodb/releases/tag/v2.0.7
=> chore: add akka-persistence-dynamodb-s3-fallback-store module

project/Dependencies.scala
- https://github.com/akka/akka-persistence-dynamodb/issues/167
- https://github.com/akka/akka-persistence-dynamodb/releases/tag/v2.0.8
=> bump: akka-persistence-dynamodb 2.0.8

project/Dependencies.scala
References https://github.com/akka/akka/issues/32767
=> bump: Akka 2.10.8

project/Dependencies.scala
References https://github.com/akka/akka-grpc/issues/2079
=> bump: Akka gRPC 2.5.7

project/Dependencies.scala
References https://github.com/akka/akka-management/issues/1414
=> bump: Akka Management 1.6.3

project/Dependencies.scala
References https://github.com/akka/akka-persistence-jdbc/issues/931
=> bump: Akka Persistence JDBC 5.5.3
